version: '2'
services:

  # The Application
  app:
    build:
      context: ./docker/app
    working_dir: /var/www
    volumes:
    - ./src:/var/www

  # The Web Server
  nginx:
    build:
      context: ./docker/nginx
    working_dir: /var/www
    volumes_from:
    - app
    ports:
    - 8080:80
