version: '3'
services:

  # The Application
  app:
    build:
      context: ./docker/app
      args:
        UID: ${uid:-1000}
        GID: ${gid:-1000}
    working_dir: /var/www
    user: "${uid:-1000}:${gid:-1000}"
    volumes:
    - ./src:/var/www

  composer:
    image: composer
    command: install
    user: "${uid:-1000}:${gid:-1000}"
    volumes:
    - ./src:/app

  # The Web Server
  nginx:
    build:
      context: ./docker/nginx
    working_dir: /var/www
    volumes:
    - ./src:/var/www
    ports:
    - 8080:80
